### ISSUE TITLE
Error on interacting with Scoreboard

### ISSUE THREAD

**Issue by TechsCode** [MrMicky-FR/FastBoard#39] opened 2023-10-04 17:25 UTC
Hey! 
after your most recent changes our large community is getting the following issue:

```logs
java.lang.RuntimeException: Unable to update scoreboard title
        at me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.updateTitle(FastBoardBase.java:220) ~[UltraScoreboards.jar:?]
        at me.TechsCode.UltraScoreboards.scoreboards.FastBoard.updateTitle(FastBoard.java:71) ~[UltraScoreboards.jar:?]
        at me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$5(ScoreboardManager.java:147) ~[UltraScoreboards.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$6(ScoreboardManager.java:114) ~[UltraScoreboards.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$7(ScoreboardManager.java:114) ~[UltraScoreboards.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-45]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-45]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: This FastBoard is deleted
        at me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.sendPacket(FastBoardBase.java:537) ~[UltraScoreboards.jar:?]
        at me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.sendObjectivePacket(FastBoardBase.java:458) ~[UltraScoreboards.jar:?]
        at me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.updateTitle(FastBoardBase.java:218) ~[UltraScoreboards.jar:?]
        ... 13 more
[17:17:47 WARN]: java.lang.RuntimeException: Unable to delete scoreboard
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.delete(FastBoardBase.java:404)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$5(ScoreboardManager.java:120)
[17:17:47 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$6(ScoreboardManager.java:114)
[17:17:47 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[17:17:47 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.ScoreboardManager.lambda$start$7(ScoreboardManager.java:114)
[17:17:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:17:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:17:47 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:17:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:17:47 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:17:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:17:47 WARN]: Caused by: java.lang.IllegalStateException: This FastBoard is deleted
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.sendPacket(FastBoardBase.java:537)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.sendTeamPacket(FastBoardBase.java:507)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.sendTeamPacket(FastBoardBase.java:492)
[17:17:47 WARN]:        at UltraScoreboards.jar//me.TechsCode.UltraScoreboards.scoreboards.FastBoardBase.delete(FastBoardBase.java:399)
[17:17:47 WARN]:        ... 12 more
```

You may wonder what we have changed? As it has worked before?
Well.. we haven't changed anything expect updating the Library to its newest version.

I hope you guys can help us, multiple hundreds of users are waiting for this to get fixed.

My Discord: techscode

Thank you in advance!
Timo

**Comment by MrMicky-FR** [comment] 2023-10-04 17:52
Hi, as said in the error message, seems like you are trying to update a FastBoard instance that was previously deleted.

I'm not sure to see how this would be related to an update, as the delete code is very straightforward: this exception is only thrown if the `deleted` variable is `true`, which is the case only when the `FastBoard#delete()` method is called on an instance
https://github.com/MrMicky-FR/FastBoard/blob/56a6518e57ac6b8a9e9b83f2eaff9e08b5aac859/src/main/java/fr/mrmicky/fastboard/FastBoardBase.java#L396-L408
https://github.com/MrMicky-FR/FastBoard/blob/56a6518e57ac6b8a9e9b83f2eaff9e08b5aac859/src/main/java/fr/mrmicky/fastboard/FastBoardBase.java#L536-L538

If you have more details on how to reproduce this issue I would be happy to investigate further :)

**Comment by MrMicky-FR** [comment] 2023-10-14 14:04
I'm closing this for now, however feel free to add a comment on this issue if needed 😃

**Closed by MrMicky-FR** 2023-10-14 14:04 UTC
Labels: question

**Comment by GhostCode301** [comment] 2023-10-14 19:28
Hey, sorry for the late feedback.
As Timo mentioned, we only changed the library version of our plugin, which worked fine before. 
I saw that with the update to version 2.0 a lot has been done to the fastboard class and wondered if this might have something to do with it.

**Comment by MrMicky-FR** [comment] 2023-10-14 19:38
Yes a lot changed to add optional Adventure support, but the FastBoard deletion part wasn’t changed from what I can say. 

Do you think you could maybe provide a minimal code to reproduce the issue ? Because as said before, the scoreboard deletion part is stupidly simple (literally just boolean variable set to true when the `delete()` method is called) and I don’t see how it could cause any issue

**Comment by GhostCode301** [comment] 2023-10-14 20:05
Here is an example of what happens in the update routine
 
                String oldName = lastSb.get(player.getUniqueId());

                try {
                    if (!oldName.equals(scoreboard.getName()) && hasBoard(player)) {
                        getBoard(player).delete();
                    } else if (!hasBoard(player)) {
                        createBoard(player, UltraFormatter.format(player, scoreboard.getTitle().getLine()));
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

                FastBoard board = getBoard(player);
                if (board == null)
                    return;

                String title = UltraFormatter.format(player, scoreboard.getTitle().getLine());
                List<String> lines = scoreboard.getLines().stream().filter(l -> l.hasPermission(player)).map(l -> UltraFormatter.format(player, l.getLine())).collect(Collectors.toList());

                if (!board.isDeleted())
                    board.updateLines(lines);
                if (!board.getTitle().equals(title))
                    board.updateTitle(title);`

**Comment by MrMicky-FR** [comment] 2023-10-14 21:18
```java
if (!board.isDeleted())
    board.updateLines(lines);
if (!board.getTitle().equals(title))
    board.updateTitle(title);
```

With only the given code, this first condition doesn’t make much sense: if the scoreboard is deleted (`board.isDeleted()` returns `true`), the `board.updateLines(lines)` won’t be executed (which is good), BUT the `board.updateTitle(title)` might still be executed, even if the board is deleted, which seems to be the cause of the error (thrown by an `updateTitle` call)

**Comment by GhostCode301** [comment] 2023-10-15 09:03
thanks for the tip. this has already solved some of our problems. i will see if this helps with the other functions and get back to you. (But it might not be until later this evening, though),

**Comment by GhostCode301** [comment] 2023-10-15 16:25
Everything is working so far, thanks for the quick help.
