### ISSUE TITLE
If the lines of board decrease, the client will be kicked

### ISSUE THREAD

**Issue by LoliColleen** [MrMicky-FR/FastBoard#44] opened 2023-12-16 09:04 UTC
```java
public static void sendBoard1(Player player) {
        if (!boards.containsKey(player)) {
            var board = new FastBoard(player);
            board.updateTitle("Test");
            boards.put(player, board);
        }
        var board = boards.get(player);
        board.updateLines(
                "",
                ""
                )
                )
        );
    }

public static void sendBoard2(Player player) {
        if (!boards.containsKey(player)) {
            var board = new FastBoard(player);
            board.updateTitle("Test");
            boards.put(player, board);
        }
        var board = boards.get(player);
        board.updateLines(
                ""
                )
                )
        );
    }
```

```log
[16:42:34 ERROR]: [/139.226.16.222:31638|Kolleen] <-> DownstreamBridge <-> [Duels#1] - exception caught Type: FastDecoderException
[16:42:34 ERROR]: net.md_5.bungee.protocol.FastDecoderException: Error decoding packet ID(5b) Type(class net.md_5.bungee.protocol.packet.ScoreboardScore)
[16:42:34 ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Packet GAME:TO_CLIENT/91 (ScoreboardScore) larger than expected, extra bytes: 11
```

WaterFall Proxy, Paper Server, 1.20.1 Fabric Client
run sendBoard1 method and then run sendBoard2 method, the player will be kicked

**Comment by MrMicky-FR** [comment] 2023-12-16 10:27
Hello, will investigate this, what’s the Paper version behind the proxy?

**Comment by LoliColleen** [comment] 2023-12-16 10:41
Paper 1.20.4 Latest
Waterfall Latest

**Comment by MrMicky-FR** [comment] 2023-12-22 13:08
Which plugin (and version) are you using to allow older Minecraft clients to join ?

**Comment by LoliColleen** [comment] 2023-12-22 14:33
ViaVersion 4.9.2 and ViaBackwards 4.9.2

**Comment by MrMicky-FR** [comment] 2023-12-22 14:37
Noted, and does this issue occurs when connecting with a 1.20.4 client ?

**Comment by LoliColleen** [comment] 2023-12-23 19:59
No. At least what I found is this issue only occurs when the client's version is lower than server's version

**Comment by MrMicky-FR** [comment] 2023-12-23 22:18
I cannot reproduce with latest PaperMC (1.20.4 build 342), WaterFall (1.20 build 559) ViaVersion (build 365) and ViaBackwards (build 762), with Via on the backend (PaperMC) server.

Could you try updating Waterfall and ViaBackwards ? Because some commits are related to ScoreboardScore packet which might be the cause.

Also the error only occurs on lower clients it is most likely not related to FastBoard, as FastBoard (like most plugins) doesn't play with the client version, the only version that matters is the server version

**Comment by LoliColleen** [comment] 2023-12-25 04:57
Thank you very much, I will try it soon

**Comment by MrMicky-FR** [comment] 2024-01-23 15:38
Hi, any updates ?

**Comment by LoliColleen** [comment] 2024-01-23 20:44
Hey, but the issue still exists. I think its because of the bungeecord version. I m using a fork of bungeecord so that it may not be the latest. Maybe this issue can be closed any way. If the problem happens again I will tell you.

**Comment by MrMicky-FR** [comment] 2024-01-24 07:54
Ok I’m closing this for now but feel free to comment if you have any updates (and I can reopen if needed)

**Closed by MrMicky-FR** 2024-01-24 07:54 UTC
Labels: question
